version: '3.7'
services:
  musicstore:
    container_name: musicstore
    build: .
    image: musicstore:latest
    ports:
      - 8080:8080
    networks:
      - musicstore-network
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    networks:
      - musicstore-network
    environment:
      - MYSQL_ROOT_PASSWORD=lozinka
      - MYSQL_DATABASE=database
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
volumes:
  mysql-data:
networks:
  musicstore-network:
    driver: bridge